<a href="https://colab.research.google.com/github/krithikasanga/capestone_projects_ml/blob/main/slr_scratch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd


df=pd.read_csv("/content/placement (1).csv")

In [ ]:
df.head()

   cgpa  package
0  6.89     3.26
1  5.12     1.98
2  7.82     3.25
3  7.42     3.67
4  6.94     3.57

In [ ]:
x=df.iloc[:,0]
x

0      6.89
1      5.12
2      7.82
3      7.42
4      6.94
       ...
195    6.93
196    5.89
197    7.21
198    7.63
199    6.22
Name: cgpa, Length: 200, dtype: float64

In [ ]:
y=df.iloc[:,1]
y

0      3.26
1      1.98
2      3.25
3      3.67
4      3.57
       ...
195    2.46
196    2.57
197    3.24
198    3.96
199    2.33
Name: package, Length: 200, dtype: float64

In [ ]:
#train test split
from sklearn.model_selection import train_test_split

x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=2)

In [ ]:
x_test.shape

(40,)

In [ ]:
x_train.shape

(160,)

In [ ]:
x_train.shape[0]

160

$$
m = \frac{\sum (x_i - \bar{x})(y_i - \bar{y})}{\sum (x_i - \bar{x})^2}
$$

$$
b = \bar{y} - m\bar{x}
$$

In [ ]:
class Lr:

    def __init__(self):
        self.m = None
        self.b = None

    def fit(self, x_train, y_train):
        num = 0
        den = 0

        for i in range(x_train.shape[0]):
            num = num + ((x_train.iloc[i] - x_train.mean()) * (y_train.iloc[i] - y_train.mean()))
            den = den + ((x_train.iloc[i] - x_train.mean()) * (x_train.iloc[i] - x_train.mean()))

        self.m = num / den
        self.b = y_train.mean() - (self.m * x_train.mean())

        print("coef_ =", self.m)
        print("intercept_ =", self.b)

    def predict(self, x_test):
        print(self.m * x_test + self.b)

In [ ]:
lr=Lr()

In [ ]:
lr.fit(x_train,y_train)

coef_ = 0.5579519734250721
intercept_ = -0.8961119222429152

In [ ]:
lr.predict(x_test.iloc[0])

3.891116009744203

In [ ]:
x_test.iloc[0]

np.float64(8.58)

In [ ]:
y_test.iloc[0]#almost same

np.float64(4.1)

this code can handle only slr the sklearn linear regression can handle both slr and mlr